# Generated by Django 2.0.5 on 2018-07-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180717_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actions',
            name='description',
        ),
        migrations.RemoveField(
            model_name='checklists',
            name='description',
        ),
        migrations.AddField(
            model_name='actions',
            name='attach',
            field=models.FileField(blank=True, upload_to='attach'),
        ),
        migrations.AddField(
            model_name='actions',
            name='notes',
            field=models.TextField(default='checklist notes', max_length=1500),
        ),
        migrations.AddField(
            model_name='checklists',
            name='notes',
            field=models.TextField(default='checklist notes', max_length=1500),
        ),
    ]
