# Generated by Django 2.0.5 on 2018-07-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180717_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='author',
            field=models.CharField(editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='checklists',
            name='author',
            field=models.CharField(editable=False, max_length=150),
        ),
    ]
